minimumReleaseAgeExclude:
  - '@favorodera/eslint-config@1.0.3'

shamefullyHoist: true

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - semver@6.3.1
  - nanoid@3.3.14

packages:
  - 'apps/*'
  - 'packages/*'
  - 'playgrounds/*'

nodeOptions: --max_old_space_size=4096

allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  better-sqlite3: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true

catalogs:
  peer:
    nuxt: ^4.0.0
    vue: ^3.0.0

  tools:
    '@favorodera/eslint-config': ^1.0.4
    '@nuxt/eslint': ^1.17.0
    '@nuxt/module-builder': ^1.0.3
    '@nuxt/schema': ^4.5.2
    '@tsconfig/node24': ^24.0.4
    '@types/node': ^26.1.2
    '@vitejs/plugin-vue': ^6.0.8
    '@vitest/ui': ^4.1.10
    '@vue/test-utils': ^2.4.11
    '@vue/tsconfig': ^0.9.1
    eslint: ^10.8.0
    happy-dom: ^20.11.1
    relizy: ^1.4.9
    tsdown: ^0.22.14
    turbo: ^2.10.8
    type-fest: ^5.7.0
    typescript: ^6.0.3
    vite: ^8.2.0
    vitest: ^4.1.10
    vue-tsc: ^3.3.9

  vendor:
    '@iconify-json/lucide': ^1.2.121
    '@iconify-json/simple-icons': ^1.2.93
    '@iconify-json/vscode-icons': ^1.2.69
    '@nuxt/content': ^3.15.2
    '@nuxt/image': ^2.1.0
    '@nuxt/kit': ^4.5.2
    '@nuxt/ui': ^4.10.0
    '@nuxtjs/mcp-toolkit': ^0.17.2
    '@nuxtjs/mdc': ^0.22.2
    '@nuxtjs/seo': ^5.3.10
    '@standard-schema/spec': ^1.1.0
    '@tailwindcss/vite': ^4.3.3
    '@takumi-rs/core': ^1.8.7
    '@vercel/analytics': ^2.0.1
    '@vueuse/core': ^14.4.0
    better-sqlite3: ^12.11.1
    dequal: ^2.0.3
    dot-prop: ^10.2.0
    klona: ^2.0.6
    minimark: ^1.0.0
    motion-v: ^2.3.0
    nuxt: ^4.5.2
    nuxt-llms: ^0.2.0
    nuxt-og-image: ^6.7.6
    nuxt-schema-org: ^6.2.8
    tailwindcss: ^4.3.3
    ufo: ^1.6.4
    unist-util-visit: ^5.1.0
    vue: ^3.5.41
    vue-router: ^5.2.0
    zod: ^4.4.3
peerDependencyRules:
  allowedVersions:
    typescript: '6'
    vite: '8'
