export default defineAppConfig({
  author: {
    name: 'Favour Emeka',
    url: 'https://favorodera.vercel.app',
  },
  github: {
    repo: {
      icon: 'simple-icons:github',
      label: 'GitHub',
      url: 'https://github.com/favorodera/notform',
    },
    sponsor: {
      icon: 'tabler:heart',
      label: 'Sponsor',
      url: 'https://github.com/sponsors/favorodera',
    },
  },
  siteDescription: 'Vue Forms without the friction.',
  siteName: 'NotForm',
  siteTitle: 'NotForm - Vue Forms without the friction',
  siteUrl: 'https://notformdocs.vercel.app',
  ui: {
    colors: {
      neutral: 'zinc',
    },
    icons: {
      arrowDown: 'tabler:arrow-down',
      arrowLeft: 'tabler:arrow-left',
      arrowRight: 'tabler:arrow-right',
      arrowUp: 'tabler:arrow-up',
      caution: 'tabler:alert-square-rounded',
      check: 'tabler:check',
      chevronDoubleLeft: 'tabler:chevrons-left',
      chevronDoubleRight: 'tabler:chevrons-right',
      chevronDown: 'tabler:chevron-down',
      chevronLeft: 'tabler:chevron-left',
      chevronRight: 'tabler:chevron-right',
      chevronUp: 'tabler:chevron-up',
      close: 'tabler:x',
      copy: 'tabler:copy',
      copyCheck: 'tabler:copy-check',
      dark: 'tabler:moon',
      drag: 'tabler:grip-vertical',
      ellipsis: 'tabler:dots',
      error: 'tabler:square-rounded-x',
      external: 'tabler:external-link',
      eye: 'tabler:eye',
      eyeOff: 'tabler:eye-off',
      file: 'tabler:file',
      folder: 'tabler:folder',
      folderOpen: 'tabler:folder-open',
      hash: 'tabler:hash',
      info: 'tabler:info-square-rounded',
      light: 'tabler:sun',
      loading: 'tabler:loader-2',
      menu: 'tabler:menu',
      minus: 'tabler:minus',
      panelClose: 'tabler:layout-sidebar-left-collapse',
      panelOpen: 'tabler:layout-sidebar-left-expand',
      plus: 'tabler:plus',
      reload: 'tabler:reload',
      search: 'tabler:search',
      star: 'tabler:star',
      stop: 'tabler:player-stop',
      success: 'tabler:square-rounded-check',
      system: 'tabler:device-desktop',
      tip: 'tabler:bulb',
      upload: 'tabler:upload',
      warning: 'tabler:alert-triangle',
    },
    prose: {
      codePreview: {
        slots: {
          code: '[&_pre]:rounded-t-none [&>div]:my-0 [&>div>div]:my-0',
        },
      },
    },
  },
})
