blank_issues_enabled: false

contact_links:
  - name: Documentation
    url: https://notformdocs.vercel.app/
    about: Check our documentation for guides and API reference

  - name: Questions & Discussions
    url: https://github.com/favorodera/notform/discussions
    about: Ask questions and discuss ideas

  - name: Docs Playground
    url: https://notformdocs.vercel.app/playground
    about: Experiment with NotForm in an interactive playground on the docs website

  - name: StackBlitz Playground
    url: https://stackblitz.com/edit/notform
    about: Experiment with NotForm Core in an interactive playground on stackblitz

  - name: StackBlitz Nuxt Module Playground
    url: https://stackblitz.com/edit/notform-nuxt
    about: Experiment with the NotForm Nuxt Module in an interactive playground on stackblitz
