import type { StandardSchemaV1 } from '@standard-schema/spec'
import type { ComputedRef, FormHTMLAttributes, MaybeRefOrGetter, Ref, VNodeChild } from 'vue'
import type { ObjectSchema, ValidationMode, ValidationTriggers } from './shared'
import type { DeepPartial, Paths } from './utils'

/**
 * Configuration options for initializing a new form instance.
 * @template TSchema The validation schema type derived from ObjectSchema.
 */
export type UseFormOptions<TSchema extends ObjectSchema> = {
  /** Unique form identifier (autogenerated if omitted) */
  id?: string
  /** The validation schema used to parse and validate form data */
  schema: MaybeRefOrGetter<TSchema>
  /** Initial form data values */
  initialState?: DeepPartial<StandardSchemaV1.InferInput<TSchema>>
  /** List of validation issues to display initially */
  initialErrors?: StandardSchemaV1.Issue[]
  /** Validation behavioral strategy (lazy or eager) */
  mode?: ValidationMode
  /** Events that trigger individual field validation */
  validateOn?: ValidationTriggers[]
  /**
   * Custom validation logic that runs after schema validation.
   * @param data The validated data from the schema.
   * @returns Success boolean, issues array, or void.
   */
  onValidate?: (data: StandardSchemaV1.InferOutput<TSchema>) => boolean | void | StandardSchemaV1.Issue[] | Promise<boolean | void | StandardSchemaV1.Issue[]>
  /** Callback triggered when the form is reset */
  onReset?: () => void
  /**
   * Callback triggered when form validation fails.
   * @param errors The list of identified issues.
   */
  onError?: (errors: StandardSchemaV1.Issue[]) => void
}

/**
 * The core state and methods provided by a form instance.
 * @template TSchema The validation schema type derived from ObjectSchema.
 */
export type FormContext<TSchema extends ObjectSchema> = {
  /** Unique form identifier */
  id: string
  /** Deeply reactive object of field values */
  state: Ref<StandardSchemaV1.InferInput<TSchema>>
  /**
   * Updates the form state.
   * @param _state The new state to apply.
   * @param _validate Re-validate after update (default: true).
   */
  setState: (_state: DeepPartial<StandardSchemaV1.InferInput<TSchema>>, _validate?: boolean) => void
  /** Baseline form data at moment of initialization */
  initialState: StandardSchemaV1.InferInput<TSchema>
  /** Reactive array of active validation issues */
  errors: Ref<StandardSchemaV1.Issue[]>
  /**
   * Directly sets the form errors.
   * @param _errors The issues to apply.
   */
  setErrors: (_errors: StandardSchemaV1.Issue[]) => void
  /** Removes all active validation issues */
  clearErrors: () => void
  /**
   * Retrieves validation issues for a specific field.
   * @param field The path to the field.
   * @returns Array of issues for that field.
   */
  getFieldErrors: (field: Paths<StandardSchemaV1.InferInput<TSchema>>) => StandardSchemaV1.Issue[]
  /** List of issues provided during initialization */
  initialErrors: StandardSchemaV1.Issue[]
  /** Computed reference to the active validation schema */
  schema: ComputedRef<TSchema>
  /** Strategy for how/when validation occurs */
  mode: ValidationMode
  /** Interaction events configured to trigger validation */
  validateOn: ValidationTriggers[]
  /**
   * Validates entire form.
   * @returns Promise resolving to validation results.
   */
  validate: () => Promise<StandardSchemaV1.Result<StandardSchemaV1.InferOutput<TSchema>>>
  /**
   * Validates a single specified field.
   * @param field The path to the field.
   * @returns Promise resolving to validation results.
   */
  validateField: (field: Paths<StandardSchemaV1.InferInput<TSchema>>) => Promise<StandardSchemaV1.Result<StandardSchemaV1.InferOutput<TSchema>>>
  /**
   * Reverts state and errors to initial or custom baseline.
   * @param _state Optional partial state baseline.
   * @param _errors Optional issues list baseline.
   * @param _validate Re-validate after resetting (default: false).
   */
  reset: (_state?: DeepPartial<StandardSchemaV1.InferInput<TSchema>>, _errors?: StandardSchemaV1.Issue[], _validate?: boolean) => void
  /** Reactive status of async validation process */
  isValidating: Ref<boolean>
  /** Computed status of form validity */
  isValid: ComputedRef<boolean>
  /** Computed status of field interactions */
  isTouched: ComputedRef<boolean>
  /**
   * Marks a field as interacted with.
   * @param field The path to the field.
   */
  touchField: (field: Paths<StandardSchemaV1.InferInput<TSchema>>) => void
  /** Marks all fields in the form as touched */
  touchAllFields: () => void
  /** Reactive set of touched field paths */
  touchedFields: Ref<Set<Paths<StandardSchemaV1.InferInput<TSchema>>>>
  /** Computed status of form modifications */
  isDirty: ComputedRef<boolean>
  /** Reactive set of dirty field paths */
  dirtyFields: Ref<Set<Paths<StandardSchemaV1.InferInput<TSchema>>>>
  /**
   * Programmatically marks a field as dirty.
   * @param field The path to the field.
   */
  dirtyField: (field: Paths<StandardSchemaV1.InferInput<TSchema>>) => void
  /** Marks all fields in the form as dirty */
  dirtyAllFields: () => void
  /**
   * Validates and then triggers form submission.
   * @param event The original form submission event.
   * @param callback Callback executed only if validation passes.
   */
  submit: (event?: Event, callback?: (data: StandardSchemaV1.InferOutput<TSchema>) => void | Promise<void>) => Promise<void>
}

/**
 * Properties accepted by the Form component.
 * @template TSchema The validation schema type derived from ObjectSchema.
 */
export type FormProps<TSchema extends ObjectSchema> = Pick<FormContext<TSchema>, 'id'> & /* @vue-ignore */ Omit<FormHTMLAttributes, 'id'>

/**
 * Slots provided by the Form component.
 * @template TSchema The validation schema type derived from ObjectSchema.
 */
export type FormSlots<TSchema extends ObjectSchema> = {
  /** The default slot receives the form context as its scope */
  default: (props: FormContext<TSchema>) => VNodeChild
}

/**
 * Expected return type for the useForm composable.
 * @template TSchema The validation schema type derived from ObjectSchema.
 */
export type UseFormReturn<TSchema extends ObjectSchema> = FormContext<TSchema>
